-- liquibase formatted sql
-- changeset jcbbb:1
CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "first_name" varchar(255) NOT NULL,
  "last_name" varchar(255) NOT NULL,
  "email" varchar(255),
  "email_verified" boolean DEFAULT FALSE,
  "phone" varchar(255),
  "phone_verified" boolean DEFAULT FALSE,
  "password" varchar(255) NOT NULL,
  "verified" boolean DEFAULT FALSE,
  "created_at" timestamp with time zone DEFAULT NOW() NOT NULL,
  "picture" varchar(255) NOT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "sessions" (
  "id" uuid DEFAULT gen_random_uuid () NOT NULL,
  "active" boolean DEFAULT TRUE,
  "ip" inet,
  "expires_at" timestamp with time zone NOT NULL,
  "created_at" timestamp with time zone DEFAULT NOW() NOT NULL,
  "user_id" integer NOT NULL,
  CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "scopes" (
  "key" varchar(255) NOT NULL UNIQUE,
  "icon_uri" varchar(255),
  "sensitive" boolean DEFAULT FALSE,
  CONSTRAINT "permissions_pkey" PRIMARY KEY ("key")
);

CREATE TABLE "scope_translations" (
  "scope_key" varchar(255) NOT NULL,
  "lang" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL
);

CREATE TABLE "clients" (
  "id" uuid DEFAULT gen_random_uuid () NOT NULL,
  "name" varchar(255) NOT NULL,
  "secret" varchar(255) NOT NULL,
  "uri" varchar(255) NOT NULL,
  "logo_uri" varchar(255),
  "tos_uri" varchar(255),
  "policy_uri" varchar(255),
  "contacts" varchar[] DEFAULT '{}' ::character varying[],
  "token_endpoint_auth_method" varchar(255) NOT NULL CHECK (token_endpoint_auth_method IN ('client_secret_basic', 'client_secret_post', 'client_secret_jwt', 'private_key_jwt', 'none')) DEFAULT 'client_secret_basic',
  "created_at" timestamp with time zone DEFAULT NOW() NOT NULL,
  "active" boolean DEFAULT TRUE,
  "type" varchar(255) NOT NULL CHECK (type IN ('confidential', 'public')) DEFAULT 'confidential',
  CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "client_redirect_uris" (
  "client_id" uuid NOT NULL,
  "uri" varchar(255) NOT NULL
);

CREATE TABLE "grant_types" (
  "value" varchar(255) NOT NULL UNIQUE,
  CONSTRAINT "grant_types_pkey" PRIMARY KEY ("value")
);

CREATE TABLE "response_types" (
  "value" varchar(255) NOT NULL UNIQUE,
  CONSTRAINT "response_types_pkey" PRIMARY KEY ("value")
);

CREATE TABLE "authorization_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "redirect_uri" varchar(255) NOT NULL,
  "response_type" varchar(255) NOT NULL,
  "code_challenge" varchar(255) NOT NULL,
  "code_challenge_method" varchar(10) NOT NULL DEFAULT 'plain',
  "scope" text NOT NULL,
  "state" text,
  "code" integer UNIQUE,
  "client_id" uuid NOT NULL,
  "user_id" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT NOW() NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "used" boolean DEFAULT FALSE,
  CONSTRAINT "authorization_requests_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "tokens" (
  "id" uuid DEFAULT gen_random_uuid () NOT NULL,
  "sub" integer NOT NULL,
  "aud" varchar(255) NOT NULL,
  "client_id" uuid NOT NULL,
  "scope" text,
  "authorization_request_id" integer,
  "refresh_token" uuid DEFAULT gen_random_uuid () NOT NULL,
  "created_at" timestamp with time zone DEFAULT NOW() NOT NULL,
  "iat" timestamp with time zone DEFAULT now() NOT NULL,
  "exp" timestamp with time zone NOT NULL,
  CONSTRAINT "tokens_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "client_scopes" (
  client_id uuid NOT NULL,
  scope_key varchar(255) NOT NULL
);

CREATE TABLE "client_grant_types" (
  client_id uuid NOT NULL,
  grant_type varchar(255) NOT NULL
);

CREATE TABLE "client_response_types" (
  client_id uuid NOT NULL,
  response_type varchar(255) NOT NULL
);

ALTER TABLE "tokens"
  ADD CONSTRAINT "fk_client" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON UPDATE NO action ON DELETE CASCADE;

ALTER TABLE "tokens"
  ADD CONSTRAINT "fk_authorization_request" FOREIGN KEY ("authorization_request_id") REFERENCES "authorization_requests" ("id") ON UPDATE NO action ON DELETE CASCADE;

ALTER TABLE "client_redirect_uris"
  ADD CONSTRAINT "fk_client" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON UPDATE NO action ON DELETE CASCADE;

ALTER TABLE "authorization_requests"
  ADD CONSTRAINT "fk_response_type" FOREIGN KEY ("response_type") REFERENCES "response_types" ("value") ON UPDATE NO action ON DELETE CASCADE;

ALTER TABLE "scope_translations"
  ADD CONSTRAINT "fk_scope" FOREIGN KEY ("scope_key") REFERENCES "scopes" ("key") ON UPDATE NO action ON DELETE CASCADE;

ALTER TABLE "sessions"
  ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "client_scopes"
  ADD CONSTRAINT "fk_client" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "client_scopes"
  ADD CONSTRAINT "fk_scope" FOREIGN KEY ("scope_key") REFERENCES "scopes" ("key") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "client_grant_types"
  ADD CONSTRAINT "fk_client" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "client_grant_types"
  ADD CONSTRAINT "fk_grant_type" FOREIGN KEY ("grant_type") REFERENCES "grant_types" ("value") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "client_response_types"
  ADD CONSTRAINT "fk_client" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "client_response_types"
  ADD CONSTRAINT "fk_response_type" FOREIGN KEY ("response_type") REFERENCES "response_types" ("value") ON UPDATE NO ACTION ON DELETE CASCADE;

CREATE INDEX "idx_sessions_user_id" ON sessions ("user_id");

CREATE INDEX "tokens_authorization_request_id" ON "tokens" ("authorization_request_id");

CREATE UNIQUE INDEX "uidx_authorization_requests_code_redirecturi_clientid_used" ON "authorization_requests" ("code", "redirect_uri", "client_id", "used");

CREATE UNIQUE INDEX "uidx_users_email" ON users ("email");

CREATE UNIQUE INDEX "uidx_scopetranslations_scopekey_lang" ON "scope_translations" ("scope_key", "lang");

CREATE UNIQUE INDEX "uidx_users_phone" ON users ("phone");

CREATE UNIQUE INDEX "uidx_clientscopes_scopekey_clientid" ON client_scopes ("scope_key", "client_id");

CREATE UNIQUE INDEX "uidx_clientresponsetypes_responsetype_clientid" ON client_response_types ("response_type", "client_id");

CREATE UNIQUE INDEX "uidx_clientgranttypes_granttype_clientid" ON client_grant_types ("grant_type", "client_id");

CREATE UNIQUE INDEX "uidx_clientredirecturis_uri_clientid" ON client_redirect_uris ("uri", "client_id");

-- rollback DROP TABLE authorization_requests CASCADE;
-- rollback DROP TABLE clients CASCADE;
-- rollback DROP TABLE permissions CASCADE;
-- rollback DROP TABLE "privileges" CASCADE;
-- rollback DROP TABLE sessions CASCADE;
-- rollback DROP TABLE users CASCADE;
